apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s_helm.fullname" . }}
  labels:
    {{- include "k8s_helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1234
      protocol: TCP
      name: http
  selector:
    app: server
